on:
 push:
  branches:
   - master

jobs:
 minitest_port_test:
  runs-on: windows-latest
  steps: 
   - name: Checkout Atliac/vcpkg
     uses: actions/checkout@v4.1.1
     with:
      repository: Atliac/vcpkg
      ref: minitest
      path: vcpkg
   - name: vcpkg bootstrap
     run: .\vcpkg\bootstrap-vcpkg.bat
   - name: Checkout 
     uses: actions/checkout@v4.1.1
     with:
      path: test
   - name: CMake configure
     run: cmake -B build -S test -G "Visual Studio 17 2022" -A x64 "-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"
   - name: Build
     run: cmake --build build --config Release
   - name: Test
     run: ctest --test-dir build --output-on-failure
