on:
 push:
  branches:
   - master

jobs:
 minitest_port_test:
  runs-on: windows-latest
  steps: 
   - name: Checkout Atliac/vcpkg
     uses: actions/checkout@v4.1.1
     with:
      repository: Atliac/vcpkg
      ref: minitest
      path: vcpkg
   - name: vcpkg bootstrap
     run: |
      cd vcpkg
      .\bootstrap-vcpkg.bat
      cd ..
   - name: Set env CMAKE_TOOLCHAIN_FILE
     run: Set-Item -Path env:CMAKE_TOOLCHAIN_FILE -Value "D:\a\minitest_port_test\vcpkg/scripts/buildsystems/vcpkg.cmake"
   - name: Checkout 
     uses: actions/checkout@v4.1.1
   - name: Build
     run: cmake -B build -S . -G "Visual Studio 16 2019" -A x64
   - name: Test
     run: ctest --test-dir build --output-on-failure
